import Head from 'next/head';

import { Hero } from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Hero />
        <h1
          data-aos='fade-down'
          data-aos-duration='2000'
          className='text-center font-black text-gray-800 text-7xl my-20'
        >
          Coming Soon...
        </h1>
      </main>
    </div>
  );
}
