import React from 'react';
import { Nav } from '../components/layout/Nav';
import Head from 'next/head';
import { Sale } from '../components/Sale';
import { Branding } from '../components/Branding';
import { FAQ } from '../components/FAQ';
import { Workouts } from '../components/Workouts';
import Quote from '../components/Quote';
import { Footer } from '../components/layout/Footer';
import { FreeTrial } from '../components/FreeTrial';

const index = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mt-32'>
        <Nav />
        <Sale />
        <Branding />
        <Workouts />
        <FreeTrial />
        <Quote />
        <FAQ />
        <Footer />
      </main>
    </div>
  );
};

export default index;
