import React from 'react';
import Head from 'next/head';
import { TeamCard } from '../components/TeamCard';
import { Hero } from '../components/Hero';
import { Nav } from '../components/layout/Nav';
import { Team } from '../components/Team';
import { Footer } from '../components/layout/Footer';
import { Positions } from '../components/Positions';

const team = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main className='mt-32'>
        <Team />
        <Positions />
      </main>
      <Footer />
    </div>
  );
};

export default team;
